
on: [push]

jobs: 
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps: 
      - uses: webbertakken/unity-test-runner@v1.4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ~/
          unityVersion: 2020.1.2f1
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: artifacts
      - uses: actions/cache@v1.1.0
        with:
          path: ~/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-PBAG-Lite-
            Library-
