name: '💥 Purge Old Artifacts'
on:
  schedule:
    - cron: '0 4 * * *' # Purges every night at 04:00 UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 5days # Setting this to 0 will delete all artifacts
